
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Checkbutton


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../img")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def openVigenere():
    from vigenere import Vigenere
    Vigenere(window)

def openPlayfair():
    from playfair import Playfair
    Playfair(window)

def openOnetimePad():
    from otp import OnetimePad
    OnetimePad(window)

def openEnigma():
    from enigma import Enigma
    Enigma(window)

class Extended():
    def __init__(self, screen):
        self.screen = screen
        global window
        screen.destroy()

        window = Tk()

        window.title("Extended Vigenere Cipher")
        window.geometry("900x600")
        window.configure(bg = "#E8DFCA")


        canvas = Canvas(
            window,
            bg = "#E8DFCA",
            height = 600,
            width = 900,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        # judul
        canvas.place(x = 0, y = 0)
        image_image_title = PhotoImage(
            file=relative_to_assets("title.png"))
        image_title = canvas.create_image(
            97.0,
            87.0,
            image=image_image_title
        )

        # tombol vigenere
        button_image_vigenere = PhotoImage(
            file=relative_to_assets("vigenere.png"))
        button_vigenere = Button(
            image=button_image_vigenere,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: openVigenere(),
            relief="flat"
        )
        # posisi tombol vigenere
        button_vigenere.place(
            x=22.0,
            y=174.0,
            width=150.0,
            height=40.0
        )

        # tombol vigenere extended
        button_image_extended_on = PhotoImage(
            file=relative_to_assets("extended_on.png"))
        button_extended_on = Button(
            image=button_image_extended_on,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("extended_on clicked"),
            relief="flat"
        )
        # posisi tombol vigenere extended
        button_extended_on.place(
            x=22.0,
            y=249.0,
            width=150.0,
            height=40.0
        )

        # tombol playfair
        button_image_playfair = PhotoImage(
            file=relative_to_assets("playfair.png"))
        button_playfair = Button(
            image=button_image_playfair,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: openPlayfair(),
            relief="flat"
        )
        # posisi tombol platfair
        button_playfair.place(
            x=22.0,
            y=324.0,
            width=150.0,
            height=40.0
        )

        # tombol otp
        button_image_otp = PhotoImage(
            file=relative_to_assets("otp.png"))
        button_otp = Button(
            image=button_image_otp,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: openOnetimePad(),
            relief="flat"
        )
        # posisi tombol otp
        button_otp.place(
            x=22.0,
            y=399.0,
            width=150.0,
            height=40.0
        )

        # tombol enigma
        button_image_enigma = PhotoImage(
            file=relative_to_assets("enigma.png"))
        button_enigma = Button(
            image=button_image_enigma,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: openEnigma(),
            relief="flat"
        )
        # posisi tombol enigma
        button_enigma.place(
            x=22.0,
            y=475.0,
            width=150.0,
            height=40.0
        )

        # line
        canvas.create_rectangle(
            194.0,
            0.0,
            199.0,
            600.0,
            fill="#7895B2",
            outline="")

        # input label
        canvas.create_text(
            221.0,
            27.0,
            anchor="nw",
            text="Input : ",
            fill="#000000",
            font=("Poppins Regular", 15 * -1)
        )

        # tombol choose file untuk input (bisa plaintext bisa ciphertext)
        button_image_import = PhotoImage(
            file=relative_to_assets("import.png"))
        button_import = Button(
            image=button_image_import,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("import clicked"),
            relief="flat"
        )
        # posisi tombol choose file untuk input
        button_import.place(
            x=221.0,
            y=50.0,
            width=657.0,
            height=30.0
        )

        # kolom input
        entry_image_input = PhotoImage(
            file=relative_to_assets("input.png"))
        entry_bg_input = canvas.create_image(
            549.5,
            121.5,
            image=entry_image_input
        )
        # format input
        entry_input = Text(
            bd=0,
            bg="#F5EFE6",
            fg="#000716",
            font=("Poppins Regular", 15 * -1),
            highlightthickness=0
        )
        # posisi kolom input
        entry_input.place(
            x=221.0,
            y=85.0,
            width=657.0,
            height=71.0
        )

        # key label
        canvas.create_text(
            221.0,
            178.0,
            anchor="nw",
            text="Key :",
            fill="#000000",
            font=("Poppins Regular", 15 * -1)
        )

        # kolom key
        entry_image_key = PhotoImage(
            file=relative_to_assets("key.png"))
        entry_bg_key = canvas.create_image(
            549.5,
            237.5,
            image=entry_image_key
        )
        # format input key
        entry_key = Text(
            bd=0,
            bg="#F5EFE6",
            fg="#000716",
            font=("Poppins Regular", 15 * -1),
            highlightthickness=0
        )
        # posisi kolom key
        entry_key.place(
            x=221.0,
            y=201.0,
            width=657.0,
            height=71.0
        )

        # checkbutton untuk menggunakan spasi atau tidak
        check = Checkbutton(
                window,
                anchor = "nw",
                bg = "#E8DFCA",
                text = "add a space after 5 letters",
                font = ("Poppins Regular", 15 * -1)
        )
        # posisi checkbox
        check.pack()
        check.place(
            x = 222.0,
            y = 285.0
        )

        # tombol encrypt
        button_image_encrypt = PhotoImage(
            file=relative_to_assets("encrypt.png"))
        button_encrypt = Button(
            image=button_image_encrypt,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("encrypt clicked"),
            relief="flat"
        )
        # posisi tombol encrypt
        button_encrypt.place(
            x=221.0,
            y=324.0,
            width=317.0,
            height=40.0
        )

        # tombol decrypt
        button_image_decrypt = PhotoImage(
            file=relative_to_assets("decrypt.png"))
        button_decrypt = Button(
            image=button_image_decrypt,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("decrypt clicked"),
            relief="flat"
        )
        # posisi tombol decrypt
        button_decrypt.place(
            x=561.0,
            y=324.0,
            width=317.0,
            height=40.0
        )

        # output label
        canvas.create_text(
            221.0,
            384.0,
            anchor="nw",
            text="Ouput : ",
            fill="#000000",
            font=("Poppins Regular", 15 * -1)
        )

        # kolom output
        canvas.create_rectangle(
            221.0,
            407.0,
            878.0,
            480.0,
            fill="#F5EFE6",
            outline="")

        # tombol save file dari output
        button_image_save = PhotoImage(
            file=relative_to_assets("save.png"))
        button_save = Button(
            image=button_image_save,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("save clicked"),
            relief="flat"
        )
        # posisi tombol save file
        button_save.place(
            x=221.0,
            y=485.0,
            width=657.0,
            height=30.0
        )
        
        window.resizable(False, False)
        window.mainloop()
