# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"../img")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def openVigenere():
    from vigenere import Vigenere
    Vigenere(window)

def openExtended():
    from extended import Extended
    Extended(window)

def openPlayfair():
    from playfair import Playfair
    Playfair(window)

def openOnetimePad():
    from otp import OnetimePad
    OnetimePad(window)

def openEnigma():
    from enigma import Enigma
    Enigma(window)

def mainMenu(screen=None):
    if (screen != None):
        screen.destroy()
    global window
    window = Tk()
    window.title("Classic Cipher")
    window.geometry("900x600")
    window.configure(bg = "#E8DFCA")


    canvas = Canvas(
        window,
        bg = "#E8DFCA",
        height = 600,
        width = 900,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    # judul
    canvas.place(x = 0, y = 0)
    image_image_title = PhotoImage(
        file=relative_to_assets("title.png"))
    image_title = canvas.create_image(
        97.0,
        87.0,
        image=image_image_title
    )

    # tombol vigenere
    button_image_vigenere = PhotoImage(
        file=relative_to_assets("vigenere.png"))
    button_vigenere = Button(
        image=button_image_vigenere,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: openVigenere(),
        relief="flat"
    )
    # posisi tombol vigenere
    button_vigenere.place(
        x=22.0,
        y=174.0,
        width=150.0,
        height=40.0
    )

    # tombol vigenere extended
    button_image_extended = PhotoImage(
        file=relative_to_assets("extended.png"))
    button_extended = Button(
        image=button_image_extended,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: openExtended(),
        relief="flat"
    )
    # posisi tombol vigenere extended
    button_extended.place(
        x=22.0,
        y=249.0,
        width=150.0,
        height=40.0
    )

    # tombol playfair
    button_image_playfair = PhotoImage(
        file=relative_to_assets("playfair.png"))
    button_playfair = Button(
        image=button_image_playfair,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: openPlayfair(),
        relief="flat"
    )
    # posisi tombol playfair
    button_playfair.place(
        x=22.0,
        y=324.0,
        width=150.0,
        height=40.0
    )

    # tombol otp
    button_image_otp = PhotoImage(
        file=relative_to_assets("otp.png"))
    button_otp = Button(
        image=button_image_otp,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: openOnetimePad(),
        relief="flat"
    )
    # posisi tombol otp
    button_otp.place(
        x=22.0,
        y=399.0,
        width=150.0,
        height=40.0
    )

    # tombol enigma
    button_image_enigma = PhotoImage(
        file=relative_to_assets("enigma.png"))
    button_enigma = Button(
        image=button_image_enigma,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: openEnigma(),
        relief="flat"
    )
    # posisi tombol enigma
    button_enigma.place(
        x=22.0,
        y=475.0,
        width=150.0,
        height=40.0
    )

    # line
    canvas.create_rectangle(
        194.0,
        0.0,
        199.0,
        600.0,
        fill="#7895B2",
        outline="")

    # welcome
    image_image_welcome = PhotoImage(
        file=relative_to_assets("welcome.png"))
    image_welcome = canvas.create_image(
        560.0,
        300.0,
        image=image_image_welcome
    )
    window.resizable(False, False)
    window.mainloop()
if __name__ == "__main__":
    mainMenu()
